In [1]:
import pandas as pd
Tx = pd.read_csv('C:\\Users\\scsi_public\\Desktop\\intern\\taxinew\\take_morning.csv')
Tx

code  name            name_eng  base_year      area  NUMPOINTS  \
0    1125074    길동            Gil-dong       2013   2016761         27   
1    1125073  천호2동   Cheonho 2(i)-dong       2013   2314866         37   
2    1125072  암사1동     Amsa 1(il)-dong       2013    928971         11   
3    1125071  둔촌2동   Dunchon 2(i)-dong       2013   2006328          5   
4    1125070  둔촌1동  Dunchon 1(il)-dong       2013   1130989          1   
..       ...   ...                 ...        ...       ...        ...   
418  1101057   무악동           Muak-dong       2013    573612         19   
419  1101056   평창동    Pyeongchang-dong       2013  11389845         21   
420  1101055   부암동           Buam-dong       2013   2818336          4   
421  1101054   삼청동      Samcheong-dong       2013   1762764         19   
422  1101053   사직동          Sajik-dong       2013   1489723         76   

         xcoord     ycoord  
0    127.148021  37.536961  
1    127.124382  37.541924  
2    127.136699  37.549045  
3    127.149491  37.528695  
4    127.142559  37.520337  
..          ...        ...  
418  126.960912  37.574918  
419  126.971394  37.611266  
420  126.964722  37.593979  
421  126.983247  37.585088  
422  126.972154  37.571349  

[423 rows x 8 columns]

In [2]:
from pysal.esda.getisord import G_Local
import numpy as np
np.random.seed(12345)


C:\Users\scsi_public\anaconda3\lib\site-packages\pysal\__init__.py:58: VisibleDeprecationWarning: PySAL's API will be changed on 2018-12-31. The last release made with this API is version 1.14.4. A preview of the next API version is provided in the `pysal` 2.0 prelease candidate. The API changes and a guide on how to change imports is provided at https://pysal.org/about
  warn("PySAL's API will be changed on {}. The last "


In [3]:
y = Tx["NUMPOINTS"]
y = y.values
y

array([ 27,  37,  11,   5,   1,  14,  23,  13,  19,  21,  21,  19,   1,
        13,   4,   8,  12,   9,  42,  67,   6,  51,  29,  28,  12,  30,
         9,   6,  15,  24,  40,  19,  10,  10,  22,  18,  26,  20,   4,
         1,   2,   9,  42,  25,   3,  39, 113, 102,  23,  30,  13,  19,
        11,  10,   5,  21,  29,  66, 154,  36,  24, 100,  41,  65,  85,
        75,  14,  33,  41,  21,   6,   9,  11,  18,  36,  51,  32,  69,
        18, 116,  86,  73,  57,  20,  18,  10,   4,   9,  10,  18,   9,
        28,   6,  32,   8,  20,   7,  16,   0,   7,  15,   5,  14,   2,
        15,  23,  24,  15,  20,  13,  17,   4,   4,  18,  16,   8,   2,
         4,  25,  16,  28,  14, 119,  22,  20,  15,   6,   8,  11,  15,
         3,   8,  36,  82,  22,  72,  34, 163,   3,   0,   1,  10,  23,
         6,  17,  11,  31,  15,   4,  22,  15,   2,   0,   7,   3,   6,
        10,   2,  26,  10,  15,   7,  16,  43,  51,  33,  63,  24,  26,
        60,  35,  49, 122,  11,  47,  24,  23,  13,  11,  21,  2

In [5]:
import pysal
w = pysal.open('C:/Users/scsi_public/anaconda3/Lib/site-packages/pysal/examples/stl/seoul.gwt').read()

In [6]:
from pysal.esda.getisord import G_Local
np.random.seed(12345)
lg = G_Local(y, w)
lg.n


423

In [7]:
lg

In [165]:
from sklearn.preprocessing import StandardScaler

In [166]:
x = lg.p_sim
x

array([0.024, 0.262, 0.052, 0.022, 0.09 , 0.223, 0.121, 0.222, 0.078,
       0.007, 0.087, 0.29 , 0.024, 0.025, 0.005, 0.053, 0.021, 0.011,
       0.378, 0.33 , 0.422, 0.452, 0.396, 0.292, 0.021, 0.114, 0.009,
       0.004, 0.496, 0.077, 0.495, 0.491, 0.35 , 0.479, 0.001, 0.083,
       0.366, 0.127, 0.001, 0.016, 0.007, 0.014, 0.466, 0.394, 0.17 ,
       0.077, 0.011, 0.001, 0.356, 0.165, 0.356, 0.23 , 0.313, 0.286,
       0.343, 0.002, 0.005, 0.001, 0.001, 0.002, 0.008, 0.001, 0.006,
       0.001, 0.001, 0.001, 0.256, 0.332, 0.128, 0.397, 0.455, 0.232,
       0.5  , 0.416, 0.012, 0.001, 0.003, 0.001, 0.36 , 0.001, 0.001,
       0.098, 0.001, 0.003, 0.002, 0.001, 0.001, 0.001, 0.001, 0.002,
       0.046, 0.001, 0.001, 0.001, 0.001, 0.001, 0.003, 0.001, 0.002,
       0.001, 0.001, 0.002, 0.005, 0.001, 0.001, 0.024, 0.405, 0.261,
       0.002, 0.003, 0.158, 0.009, 0.002, 0.007, 0.001, 0.002, 0.007,
       0.031, 0.001, 0.496, 0.193, 0.496, 0.069, 0.069, 0.294, 0.001,
       0.024, 0.287,

In [167]:
scaler = StandardScaler()
x = np.reshape(x, (-1,1))
lg_scale = scaler.fit_transform(x)
lg_scale

array([[-8.05555472e-01],
       [ 6.61706281e-01],
       [-6.32936442e-01],
       [-8.17885403e-01],
       [-3.98667759e-01],
       [ 4.21272632e-01],
       [-2.07553833e-01],
       [ 4.15107667e-01],
       [-4.72647343e-01],
       [-9.10359883e-01],
       [-4.17162655e-01],
       [ 8.34325310e-01],
       [-8.05555472e-01],
       [-7.99390507e-01],
       [-9.22689814e-01],
       [-6.26771477e-01],
       [-8.24050368e-01],
       [-8.85700022e-01],
       [ 1.37684226e+00],
       [ 1.08092392e+00],
       [ 1.64810074e+00],
       [ 1.83304970e+00],
       [ 1.48781164e+00],
       [ 8.46655241e-01],
       [-8.24050368e-01],
       [-2.50708591e-01],
       [-8.98029952e-01],
       [-9.28854779e-01],
       [ 2.10430817e+00],
       [-4.78812309e-01],
       [ 2.09814321e+00],
       [ 2.07348335e+00],
       [ 1.20422323e+00],
       [ 1.99950376e+00],
       [-9.47349675e-01],
       [-4.41822517e-01],
       [ 1.30286268e+00],
       [-1.70564041e-01],
       [-9.4

In [168]:
len(lg.Gs)

423

In [169]:
Tx['Local_G'] = lg_scale
Tx

code  name            name_eng  base_year      area  NUMPOINTS  \
0    1125074    길동            Gil-dong       2013   2016761         27   
1    1125073  천호2동   Cheonho 2(i)-dong       2013   2314866         37   
2    1125072  암사1동     Amsa 1(il)-dong       2013    928971         11   
3    1125071  둔촌2동   Dunchon 2(i)-dong       2013   2006328          5   
4    1125070  둔촌1동  Dunchon 1(il)-dong       2013   1130989          1   
..       ...   ...                 ...        ...       ...        ...   
418  1101057   무악동           Muak-dong       2013    573612         19   
419  1101056   평창동    Pyeongchang-dong       2013  11389845         21   
420  1101055   부암동           Buam-dong       2013   2818336          4   
421  1101054   삼청동      Samcheong-dong       2013   1762764         19   
422  1101053   사직동          Sajik-dong       2013   1489723         76   

         xcoord     ycoord   Local_G  
0    127.148021  37.536961 -0.805555  
1    127.124382  37.541924  0.661706  
2    127.136699  37.549045 -0.632936  
3    127.149491  37.528695 -0.817885  
4    127.142559  37.520337 -0.398668  
..          ...        ...       ...  
418  126.960912  37.574918 -0.725411  
419  126.971394  37.611266 -0.034935  
420  126.964722  37.593979  1.068594  
421  126.983247  37.585088 -0.713081  
422  126.972154  37.571349 -0.503472  

[423 rows x 9 columns]

In [170]:
 Tx.to_csv("C:/Users/scsi_public/anaconda3/Lib/site-packages/pysal/examples/stl/Tx_LocalG.csv", index = False, encoding='cp949')

PermissionError: [Errno 13] Permission denied: 'C:/Users/scsi_public/anaconda3/Lib/site-packages/pysal/examples/stl/Tx_LocalG.csv'

In [171]:
np.percentile(Tx['Local_G'], [10, 20, 30, 70, 80, 90], interpolation ='linear')

array([-0.94734968, -0.92885478, -0.85734118,  0.60128962,  1.08832188,
        1.60987795])